MVC5CourseHomework/Models/客戶聯絡人.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5CourseHomework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }
        public string 職稱 { get; set; }
        public string 姓名 { get; set; }
        public string Email { get; set; }
        public string 手機 { get; set; }
        public string 電話 { get; set; }
        public bool 是否已刪除 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}

MVC5CourseHomework/Models/客戶聯絡人ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC5CourseHomework.Models
{
    public class 客戶聯絡人ViewModel
    {
        [Required]
        public int Id { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [Required]
        public string 職稱 { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [Required]
        public string 姓名 { get; set; }

        [StringLength(250, ErrorMessage = "欄位長度不得大於 250 個字元")]
        [Required]
        [EmailAddress(ErrorMessage = "你輸入的 E-Mail 格是不正確")]
        public string Email { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [RegularExpression(@"^09\d{2}-\d{6}", ErrorMessage = "你輸入的格式不正確，格式為 09 開頭加 8 碼數字")]
        public string 手機 { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [RegularExpression(@"^[0]\d{8,9}", ErrorMessage = "你輸入的格式不正確，格式為 0 開頭加 8 或 9 碼數字")]
        public string 電話 { get; set; }

        public string 客戶名稱 { get; set; }
    }
}

MVC5CourseHomework/Controllers/客戶聯絡人Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ClosedXML.Excel;
using MVC5CourseHomework.Helpers;
using MVC5CourseHomework.Models;

namespace MVC5CourseHomework.Controllers
{
    public class 客戶聯絡人Controller : Controller
    {
        //private 客戶資料Entities db = new 客戶資料Entities();

        // 使用 Repository Pattern 管理所有新刪查改(CRUD)等功能
        客戶聯絡人Repository custContactRepo;
        客戶資料Repository customerRepo;

        public 客戶聯絡人Controller()
        {
            custContactRepo = RepositoryHelper.Get客戶聯絡人Repository();
            customerRepo = RepositoryHelper.Get客戶資料Repository();
        }

        // GET: 客戶聯絡人
        public ActionResult Index(string sortOrder)
        {
            var data = custContactRepo.All();

            var jobTitle = custContactRepo.GetJobTitle();
            ViewBag.contactTitle = new SelectList(jobTitle);

            var customerName = custContactRepo.GetCustName();
            ViewBag.custName = new SelectList(customerName);

            ViewBag.jobTitleSortParm = String.IsNullOrEmpty(sortOrder) ? "jobTitle_desc" : "";
            ViewBag.nameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.emailSortParm = String.IsNullOrEmpty(sortOrder) ? "email_desc" : "";
            ViewBag.phoneNumSortParm = String.IsNullOrEmpty(sortOrder) ? "phone_desc" : "";
            ViewBag.telNumSortParm = String.IsNullOrEmpty(sortOrder) ? "telNum_desc" : "";
            ViewBag.customerNameSortParm = String.IsNullOrEmpty(sortOrder) ? "customerName_desc" : "";

            switch (sortOrder)
            {
                case "jobTitle_desc":
                    data = data.OrderByDescending(o => o.職稱);
                    break;
                case "name_desc":
                    data = data.OrderByDescending(o => o.姓名);
                    break;
                case "email_desc":
                    data = data.OrderByDescending(o => o.Email);
                    break;
                case "phone_desc":
                    data = data.OrderByDescending(o => o.手機);
                    break;
                case "telNum_desc":
                    data = data.OrderByDescending(o => o.電話);
                    break;
                case "customerName_desc":
                    data = data.OrderByDescending(o => o.客戶資料);
                    break;
                default:
                    data = data.OrderByDescending(o => o.客戶Id);
                    break;
            }

          
            return View(data.ToList());
        }

        //客戶聯絡人新增搜尋功能
        public ActionResult Search(string submit, string contactName, string contactPhone, string contactTel, 
            string contactTitle, string custName)
        {
           
            var data = custContactRepo.Search(contactName, contactPhone, contactTel, contactTitle, custName);

            var jobTitle = custContactRepo.GetJobTitle();
            ViewBag.contactTitle = new SelectList(jobTitle);

            var customerName = custContactRepo.GetCustName();
            ViewBag.custName = new SelectList(customerName);

            if (submit.Equals("Search"))
            {
                return View("Index", data);
            }
            else
            {
                string outputsTime = DateTime.Now.ToString("yyyyMMdd_HHmmss");

                ExcelExportHelper excelExportHelper = new ExcelExportHelper();

                var exportData =
                    data.Select(s => new 客戶聯絡人ViewModel()
                    {
                        Id = s.Id,
                        職稱 = s.職稱,
                        姓名 = s.姓名,
                        Email = s.Email,
                        手機 = s.手機,
                        電話 = s.電話,
                        客戶名稱 = s.客戶資料.客戶名稱
                    })
                    .ToList();

                var memoryStream = excelExportHelper.Stream(exportData);

                return File(
                    memoryStream.ToArray(),
                    "application/vnd.ms-excel",
                    $"Export_客戶聯絡人_{outputsTime}.xlsx");
            }
        }

        // GET: 客戶聯絡人/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = custContactRepo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Create
        public ActionResult Create()
        {
            var customer = customerRepo.All();
            ViewBag.客戶Id = new SelectList(customer, "Id", "客戶名稱");
            return View();
        }

        // POST: 客戶聯絡人/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                custContactRepo.Add(客戶聯絡人);
                custContactRepo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            var customer = customerRepo.All();
            ViewBag.客戶Id = new SelectList(customer, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = custContactRepo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            var customer = customerRepo.All();
            ViewBag.客戶Id = new SelectList(customer, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // POST: 客戶聯絡人/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                var db = custContactRepo.UnitOfWork.Context;
                db.Entry(客戶聯絡人).State = EntityState.Modified;
                custContactRepo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            var customer = customerRepo.All();
            ViewBag.客戶Id = new SelectList(customer ,"Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 =custContactRepo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // POST: 客戶聯絡人/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶聯絡人 客戶聯絡人 = custContactRepo.Find(id);
            custContactRepo.Delete(客戶聯絡人);
            custContactRepo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }

        /*
        //使用 ClosedXML 這個 NuGet 套件實作資料匯出功能，每個清單頁上都要有可以匯出 Excel 檔案的功能，要用到 FileResult 下載檔案
        public ActionResult Export(string contactName, string contactPhone, string contactTel, string contactTitle, string custName)
        {
            using (XLWorkbook wb = new XLWorkbook())
            {
                int timeStamp = Convert.ToInt32(DateTime.UtcNow.AddHours(8).Subtract(new DateTime(1970, 1, 1)).TotalSeconds);

                string outputsTime = DateTime.Now.ToString("yyyyMMdd_HHmmss");

                var data = custContactRepo
                    .Search(contactName, contactPhone, contactTel, contactTitle, custName)
                    .Select(s => new { s.Id, s.職稱, s.姓名, s.Email, s.手機, s.電話, s.客戶資料.客戶名稱 });

                var ws = wb.Worksheets.Add("custdata", 1);

                //欄位名稱
                ws.Cell("A1").Value = "Id";
                ws.Cell("B1").Value = "職稱";
                ws.Cell("C1").Value = "姓名";
                ws.Cell("D1").Value = "Email";
                ws.Cell("E1").Value = "手機";
                ws.Cell("F1").Value = "電話";
                ws.Cell("G1").Value = "客戶名稱";

                ws.Cell(2, 1).InsertData(data);

                using (MemoryStream memoryStream = new MemoryStream())
                {
                    wb.SaveAs(memoryStream);
                    memoryStream.Seek(0, SeekOrigin.Begin);

                    return File(
                        memoryStream.ToArray(),
                        "application/vnd.ms-excel",
                        $"Export_客戶聯絡人_{outputsTime}.xlsx");
                }
            }
            
        }
        */

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                custContactRepo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC5CourseHomework/Views/客戶聯絡人/Create.cshtml
@model MVC5CourseHomework.Models.客戶聯絡人

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC5CourseHomework/Views/客戶聯絡人/Delete.cshtml
@model MVC5CourseHomework.Models.客戶聯絡人

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC5CourseHomework/Views/客戶聯絡人/Details.cshtml
@model MVC5CourseHomework.Models.客戶聯絡人

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC5CourseHomework/Views/客戶聯絡人/Edit.cshtml
@model MVC5CourseHomework.Models.客戶聯絡人

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC5CourseHomework/Views/客戶聯絡人/Index.cshtml
@model IEnumerable<MVC5CourseHomework.Models.客戶聯絡人>

@{
    ViewBag.Title = "Index";
}

<h2>客戶聯絡人</h2>

@using (Html.BeginForm("Search", "客戶聯絡人"))
{
<div class="form-inline">
    @Html.DropDownList("contactTitle", null, "-- 請選擇職稱 --", htmlAttributes: new { @class = "form-control" })
    @Html.DropDownList("custName", null, "-- 請選擇客戶名稱 --", htmlAttributes: new { @class = "form-control" })

    @Html.TextBox("contactName", null, new { @class = "form-control", placeholder = "請輸入聯絡人姓名" })
    @Html.TextBox("contactPhone", null, new { @class = "form-control", placeholder = "請輸入手機號碼" })
    @Html.TextBox("contactTel", null, new { @class = "form-control", placeholder = "請輸入電話號碼" })

    <button type="submit" class="btn btn-primary" name="submit" value="Search">搜尋</button>
    <button type="submit" class="btn btn-success" name="submit" value="Export">匯出 Excel</button>
</div>
}

<br />
<p class="text-left">
    @Html.ActionLink("Create new", "Create", null, new { @class = "btn btn-primary" })
    @*<a href="@Url.Action("Export")" class="btn btn-success">匯出 Excel</a>*@
</p>

<table class="table table-bordered table-hover">
    <tr style="background-color:#8fc2f8">
        <th>
            @Html.ActionLink("職稱", "Index", new { sortOrder = ViewBag.jobTitleSortParm })
        </th>
        <th>
            @Html.ActionLink("姓名", "Index", new { sortOrder = ViewBag.nameSortParm })
           
        </th>
        <th>
            @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.emailSortParm })
           
        </th>
        <th>
            @Html.ActionLink("手機", "Index", new { sortOrder = ViewBag.phoneNumSortParm })
            
        </th>
        <th>
            @Html.ActionLink("電話", "Index", new { sortOrder = ViewBag.telNumSortParm })
           
        </th>
        <th>
            @Html.ActionLink("客戶名稱", "Index", new { sortOrder = ViewBag.customerNameSortParm })
            
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.職稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.姓名)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.手機)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }, new { @class = "btn btn-primary" }) 
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new { @class = "btn btn-info" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-warning" })
        </td>
    </tr>
}

</table>