MVC5CourseHomework/Models/客戶資料.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5CourseHomework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }
    
        public int Id { get; set; }
        public string 客戶名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 電話 { get; set; }
        public string 傳真 { get; set; }
        public string 地址 { get; set; }
        public string Email { get; set; }
        public bool 是否已刪除 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
    }
}

MVC5CourseHomework/Models/客戶資料ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MVC5CourseHomework.Models
{
    public class 客戶資料ViewModel
    {
        [Required]
        public int Id { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [Required]
        public string 客戶名稱 { get; set; }

        [StringLength(8, ErrorMessage = "欄位長度不得大於 8 個字元")]
        [Required]
        [RegularExpression(@"\d{8}", ErrorMessage = "你輸入的格式不正確，格式為 8 碼數字")]
        public string 統一編號 { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [Required]
        [RegularExpression(@"^[0]\d{8,9}", ErrorMessage = "你輸入的格式不正確，格式為 0 開頭加 8 或 9 碼數字")]
        public string 電話 { get; set; }

        [StringLength(50, ErrorMessage = "欄位長度不得大於 50 個字元")]
        [RegularExpression(@"^[0]\d{8,9}", ErrorMessage = "你輸入的格式不正確，格式為 0 開頭加 8 或 9 碼數字")]
        public string 傳真 { get; set; }

        [StringLength(100, ErrorMessage = "欄位長度不得大於 100 個字元")]
        public string 地址 { get; set; }

        [StringLength(250, ErrorMessage = "欄位長度不得大於 250 個字元")]
        [EmailAddress(ErrorMessage = "你輸入的 E-Mail 格是不正確")]
        public string Email { get; set; }

        
    }
}

MVC5CourseHomework/Controllers/客戶資料Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ClosedXML.Excel;
using MVC5CourseHomework.Models;
using MVC5CourseHomework.Helpers;

namespace MVC5CourseHomework.Controllers
{
    public class 客戶資料Controller : Controller
    {
        //private 客戶資料Entities db = new 客戶資料Entities();

        //使用 Repository Pattern 管理所有新刪查改(CRUD)等功能
        客戶資料Repository customerRepo;
        客戶聯絡人Repository contactRepo;
        客戶銀行資訊Repository bankRepo;

        public 客戶資料Controller()
        {
            customerRepo = RepositoryHelper.Get客戶資料Repository();
            contactRepo = RepositoryHelper.Get客戶聯絡人Repository(customerRepo.UnitOfWork);
            bankRepo = RepositoryHelper.Get客戶銀行資訊Repository(customerRepo.UnitOfWork);
        }

        // GET: 客戶資料
        public ActionResult Index(string sortOrder)
        {
            var custName = customerRepo.GetCustomerName();
            ViewBag.custName = new SelectList(custName);
            var data = customerRepo.All();

            ViewBag.custNameSortParm = String.IsNullOrEmpty(sortOrder) ? "custName_desc" : "";
            ViewBag.unNumSortParm = String.IsNullOrEmpty(sortOrder) ? "unNum_desc" : "";
            ViewBag.telNumSortParm = String.IsNullOrEmpty(sortOrder) ? "telNum_desc" : "";
            ViewBag.faxNumSortParm = String.IsNullOrEmpty(sortOrder) ? "faxNum_desc" : "";
            ViewBag.addressSortParm = String.IsNullOrEmpty(sortOrder) ? "address_desc" : "";
            ViewBag.emailSortParm = String.IsNullOrEmpty(sortOrder) ? "email_desc" : "";

            switch (sortOrder)
            {
                case "custName_desc":
                    data = data.OrderByDescending(o => o.客戶名稱);
                    break;
                case "unNum_desc":
                    data = data.OrderByDescending(o => o.統一編號);
                    break;
                case "telNum_desc":
                    data = data.OrderByDescending(o => o.電話);
                    break;
                case "faxNum_desc":
                    data = data.OrderByDescending(o => o.傳真);
                    break;
                case "address_desc":
                    data = data.OrderByDescending(o => o.地址);
                    break;
                case "email_desc":
                    data = data.OrderByDescending(o => o.Email);
                    break;
                default:
                    data = data.OrderBy(o => o.Id);
                    break;
            }


           
            return View(data.ToList());
        }

        //對客戶資料新增搜尋功能
        public ActionResult Search(string submit, string custName, string custUid, string custTel, string custFax, 
                    string custAddress, string custEmail)
        {
            var data = customerRepo.Search(custName, custUid, custTel, custFax, custAddress, custEmail);

            var custNameList = customerRepo.GetCustomerName();
            ViewBag.custName = new SelectList(custNameList);

            //指定由那一個View顯示查詢結果
            if (submit.Equals("Search"))
            {
                return View("Index", data);
            }
            else
            {
                int timeStamp = Convert.ToInt32(DateTime.UtcNow.AddHours(8).Subtract(new DateTime(1970, 1, 1)).TotalSeconds);
                string outputsTime = DateTime.Now.ToString("yyyyMMdd_HHmmss");

                ExcelExportHelper excelExportHepler = new ExcelExportHelper();

                var exportData =
                    data.Select(s => new 客戶資料ViewModel()
                    {
                        Id = s.Id,
                        客戶名稱 = s.客戶名稱,
                        統一編號 = s.統一編號,
                        電話 = s.電話,
                        傳真 = s.傳真,
                        地址 = s.地址,
                        Email = s.Email,
                    })
                    .ToList();

                var memoryStream = excelExportHepler.Stream(exportData);

                return File(
                   memoryStream.ToArray(),
                   "application/vnd.ms-excel",
                   $"Export_客戶資料_{outputsTime}.xlsx");

            }
            
        }


        //新增客戶清單列表
        public ActionResult CustomerList()
        {
            var contact = contactRepo.All();
            var bank = bankRepo.All();
            var data = customerRepo.GetContactBankCount(contact, bank);
          
            return View("CustomerList", data);

        }

        
        // GET: 客戶資料/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = customerRepo.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: 客戶資料/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                customerRepo.Add(客戶資料);
                customerRepo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            return View(客戶資料);
        }

        // GET: 客戶資料/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = customerRepo.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                var db = customerRepo.UnitOfWork.Context;
                db.Entry(客戶資料).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = customerRepo.Find(id.Value);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶資料 客戶資料 = customerRepo.Find(id);
            customerRepo.Delete(客戶資料);
            customerRepo.UnitOfWork.Commit();

            return RedirectToAction("Index");
          
        }

        /*
        // 使用 ClosedXML 這個 NuGet 套件實作資料匯出功能，每個清單頁上都要有可以匯出 Excel 檔案的功能，要用到 FileResult 下載檔案
        public ActionResult Export(string custName, string custUid, string custTel, string custFax,
            string custAddress, string custEmail)
        {
            // 建立Excel
            using (XLWorkbook wb = new XLWorkbook())
            {
                string outputsTime = DateTime.Now.ToString("yyyyMMdd_HHmmss");

                var data = customerRepo
                    .Search(custName, custUid, custTel, custFax, custAddress, custEmail)
                    .Select(s => new { s.Id, s.客戶名稱, s.統一編號, s.電話, s.傳真, s.地址, s.Email });

                var sheet = wb.Worksheets.Add("客戶資料表", 1);

                //修改標題列Style
                var header = sheet.Range("A1:G1");
                header.Style.Fill.BackgroundColor = XLColor.LightBlue;
                header.Style.Font.FontColor = XLColor.Gray;
                header.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                //欄位名稱
                sheet.Cell("A1").Value = "Id";
                sheet.Cell("B1").Value = "客戶名稱";
                sheet.Cell("C1").Value = "統一編號";
                sheet.Cell("D1").Value = "電話";
                sheet.Cell("E1").Value = "傳真";
                sheet.Cell("F1").Value = "地址";
                sheet.Cell("G1").Value = "Email";

                sheet.Cell(2, 1).InsertData(data);

                //第一欄隱藏
                sheet.Column(1).Hide();
                //自動伸縮欄寬
                sheet.Column(2).AdjustToContents();
                sheet.Column(2).Width += 2;

                sheet.Column(3).AdjustToContents();
                sheet.Column(3).Width += 2;

                sheet.Column(4).AdjustToContents();
                sheet.Column(4).Width += 2;

                sheet.Column(5).AdjustToContents();
                sheet.Column(5).Width += 2;

                sheet.Column(6).AdjustToContents();
                sheet.Column(6).Width += 2;

                sheet.Column(7).AdjustToContents();
                sheet.Column(7).Width += 2;

                using (MemoryStream memoryStream = new MemoryStream())
                {
                    wb.SaveAs(memoryStream);
                    memoryStream.Seek(0, SeekOrigin.Begin);

                    return File(
                        memoryStream.ToArray(),

MVC5CourseHomework/Views/客戶資料/Create.cshtml
@model MVC5CourseHomework.Models.客戶資料

@{
    ViewBag.Title = "Create";
  
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

MVC5CourseHomework/Views/客戶資料/CustomerList.cshtml
@model IEnumerable<MVC5CourseHomework.Models.CustomerViewModel>

@{
    ViewBag.Title = "客戶清單列表";
}

<h2>客戶清單列表</h2>

<table class="table table-bordered " style="width:35%">
    <tr style="background-color:#63aaf6">
        @*<th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.聯絡人數量)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.銀行帳戶數量)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.客戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.聯絡人數量)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.銀行帳戶數量)
            </td>

        </tr>
    }

</table>

MVC5CourseHomework/Views/客戶資料/Delete.cshtml
@model MVC5CourseHomework.Models.客戶資料

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC5CourseHomework/Views/客戶資料/Details.cshtml
@model MVC5CourseHomework.Models.客戶資料

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC5CourseHomework/Views/客戶資料/Edit.cshtml
@model MVC5CourseHomework.Models.客戶資料

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC5CourseHomework/Views/客戶資料/Index.cshtml
@model IEnumerable<MVC5CourseHomework.Models.客戶資料>

@{
    ViewBag.Title = "Index";
}

<h2>客戶資料</h2>

@using(Html.BeginForm("Search", "客戶資料", FormMethod.Get))
{
<div class="form-inline">
    @Html.DropDownList("custName", null, "-- 請選擇客戶名稱 --", htmlAttributes: new { @class = "form-control" })
    @Html.TextBox("custUid", null, new { @class = "form-control", placeholder = "請輸入統一編號" })
    @Html.TextBox("custTel", null, new { @class = "form-control", placeholder = "請輸入電話號碼" })
    <br /><br />
    @Html.TextBox("custFax", null, new { @class = "form-control", placeholder = "請輸入傳真號碼" })
    @Html.TextBox("custAddress", null, new { @class = "form-control", placeholder = "請輸入客戶地址" })
    @Html.TextBox("custEmail", null, new { @class = "form-control", placeholder = "請輸入Email" })
   
    <button type="submit" class="btn btn-primary" name="submit" value="Search">Search</button>
    <button type="submit" class="btn btn-success" name="submit" value="Export">Export</button>
</div>
}

<br />

<p class="text-left">
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
    @*<a href="@Url.Action("Export")" class="btn btn-success">匯出 Excel</a>*@
</p>
<table class="table table-hover table-bordered">
    <tr style="background-color:#94c1f2">
        <th>
            @Html.ActionLink("客戶名稱", "Index", new { sortOrder = ViewBag.custNameSortParm })
        </th>
        <th>
            @Html.ActionLink("統一編號", "Index", new { sortOrder = ViewBag.unNumSortParm })
           
        </th>
        <th>
            @Html.ActionLink("電話", "Index", new { sortOrder = ViewBag.telNumSortParm })
            
        </th>
        <th>
            @Html.ActionLink("傳真", "Index", new { sortOrder = ViewBag.faxNumSortParm })
           
        </th>
        <th>
            @Html.ActionLink("地址", "Index", new { sortOrder = ViewBag.addressSortParm })
           
        </th>
        <th>
            @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.emailSortParm })
           
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.統一編號)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.傳真)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.地址)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            <a href="javascript:void(0)" onclick="GetCount(@item.Id)">Count</a>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id}, new { @class="btn btn-primary" })
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new { @class = "btn btn-info" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-warning" })
        </td>
    </tr>
}

</table>

<script>
    function GetCount(id) {
        $.ajax({
            url: '/客戶資料/GetCount',
            type: "GET",
            dataType: 'json',
            data: { Id: id },
            success: function (data) {
                if (data) {
                    alert('聯絡人數量：' + data[0].聯絡人數量 + '，銀行帳戶數量：' + data[0].銀行帳戶數量);
                }
                else {
                    alert('error');
                }
            }
        });
    }
</script>